#!/bin/sh

result=~/.tmp/dict
history=~/.dict_history

show()
{
    # show the window
    window_width=830
    window_height=350
    screen_width=$(xrandr | grep "Screen 0" | cut -d "," -f 2 | cut -d " " -f 3)
    screen_height=$(xrandr | grep "Screen 0" | cut -d "," -f 2 | cut -d " " -f 5)
    eval $(xdotool getmouselocation --shell)	# get cursor location
    x_mouse=$(( $X + 30 ))	# prevent the cursor hide the text
    y_mouse=$(( $Y + 30 ))

    # check if window out of screen
    if [ $(( $y_mouse + $window_height )) -ge $screen_height ]
    then y_mouse=$(( $y_mouse - $window_height ))
    fi

    if [ $(( $x_mouse + $window_width )) -ge $screen_width ]
    then x_mouse=$(( $x_mouse - $window_width ))
    fi

    yad --text-info --show-uri --wrap --editable --no-buttons --width=$window_width --height=$window_height --posx=$x_mouse --posy=$y_mouse --filename=$result
}

# select word
if [ -z "$*" ]
then
    exit
elif [ $1 = clip ]
then
    word="$(xsel -op)"
elif [ $1 = input ]
then
    word="$(cat $history | dmenu -p 'enter the word you want to look up:')"
    echo $word | xsel -ip
fi

if [ -z "$word" ]
then
    exit
fi

# generate word meanings
dict "$word" > $result

# word histroy
if grep -q "$word" $history
then
    true
else
    echo "$word" >> $history
fi

# show word meanings
show
