#!/bin/sh

rmdir ~/Desktop # remove Desktop folder
remind &
memostatus &    # generate memo to status bar
notify-send "`date`" & # show current time
solaar --window=hide &  # logitech keyboard
xgamma -bgamma 0.5 &    # control bluelight gamma value 
redshift &  # redshift is a tool to protect your eyes
unclutter-xfixes -idle 2 &  # hide mouse if idles 2 seconds
brightnessctl set 90 &  # control brightness of the screen
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &    # launch polkit to enable authentication of desktop entry
pngphoon -w 1920 -h 1080 -f ~/.tmp/moon.png && feh --bg-fill ~/.tmp/moon.png &  # moon wallpaper
picom & # window compositor
